feat!: implement new bundle events and accessible watchers
- Adds onStart and onError microbundle js options:
onStart: is called when rollup noticed file changes and is starting with
bundling
onError: called if the rollup watcher is emitting any bundle errors

- Changes microbundle return type to:
{
  output?: string,
  watchers?: {
    "inputFileName": RollupWatcher
  }
}

- Removes obsolete rollup watch FATAL event handling